### ISSUE TITLE
Exploring the Peer-to-peer web

### ISSUE THREAD

**Issue by chartgerink** [libscie/profile-prototype#3]
During Mozilla All-Hands in Austin, @taravancil and @pfrazee are organizing a p2p event (December 14th, 2017). @taravancil kindly invited me to do a short talk about what we are working on here.

@jimpick I would like to discuss with you what would be feasible to have achieved by then. I'd love to present some of the ideas and even better if we could show some rudimentary functionality --- but I also understand I do not have a clear picture of the work needed to make steps so I told @taravancil I would discuss with you first.

Looking forward to hearing your thoughts. We can chat more about this during our sync-session later today.

**Comment by chartgerink** [comment]
Okay, talked to @jimpick and we are going to try and get something demo-able! @taravancil pinging you so you know. 

I am going to leave this issue open until after, so it can facilitate some further discussion.

**Comment by pfrazee** [comment]
Awesome. I'm going to try to get the userland WebDB toolset usable by end of tomorrow, see https://github.com/beakerbrowser/ingestdb/tree/webdb#webdb for the target API. Not sure it'll be ready/stable in time for yall to work with it, but keep an eye out -- it *might* make the demo faster to build.

**Comment by taravancil** [comment]
Yay! This is so great. December 14 is coming up soon, so if the demo isn't ready by then, an overview of your motivations and the project's architecture would still be an awesome talk.

**Comment by chartgerink** [comment]
[Presentation](https://bit.ly/p2p-austin) went well I think. Thanks again to @pfrazee and @taravancil for providing the space and pizza 🍕
